
services:

  ####################
  # Mainnet Services #
  ####################

  bitcoind:
    build:
      context: ./bitcoin
    stop_grace_period: 1m
    volumes:
      - data:/root/.bitcoin
    restart: unless-stopped
    ports: 
      - "8332:8332"

  electrs:
    build:
      context: ./electrs
    volumes:
      - data:/root/.bitcoin
      - data:/data
    restart: unless-stopped
    links:
      - bitcoind
    ports:
      - "50001:50001"

  # addrindexrs:
  #   image: counterparty/addrindexrs:v0.4.6
  #   volumes:
  #     - data:/root/.bitcoin
  #     - data:/data
  #   environment:
  #     - ADDRINDEXRS_JSONRPC_IMPORT=${ADDRINDEXRS_JSONRPC_IMPORT:-false}
  #   restart: unless-stopped
  #   links:
  #     - bitcoind
  #   ports:
  #     - "8432:8432"
  #   command:
  #     - "--indexer-rpc-host=0.0.0.0"
  #     - "--daemon-rpc-host=bitcoind"
  #     - "--cookie=rpc:rpc"
  #     - "-vvv"
  #     - "--db-dir=/data/"

  counterparty-core:
    build:
      context: .
    stop_grace_period: 1m
    volumes:
      - data:/root/.bitcoin
      - data:/data
    environment:
      - XDG_DATA_HOME=/data/
      - XDG_LOG_HOME=/data/
    restart: unless-stopped
    links:
      - bitcoind
      - electrs
      # - addrindexrs
    ports:
      - "4000:4000"                                        # API v2
      - "4100:4100"                                        # API v1
    command:
      - start
      - "--backend-connect=bitcoind"
      - "--indexd-connect=electrs"
      # - "--indexd-connect=addrindexrs"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      # - "--force" # doing too many things, better directly force in code
      # - "--catch-up=bootstrap"
      # - "--no_telemetry" # unrecognized arguments: --no_telemetry
      - "--verbose"


  ###################
  # Apps #
  ###################

  # python (flask) app
  app_flask:
    build:
      context: ./apps/python
    volumes:
      - data:/data
    ports: 
      - "3000:3000"

  # nodejs (express) app
  app_express:
    build:
      context: ./apps/nodejs
    volumes:
      - data:/data
    ports: 
      - "3001:3001"


volumes: 
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${COUNTERPARTY_DOCKER_DATA:-${XDG_DATA_HOME:-~/.local/share}}/counterparty-docker-data
